---
title: "Nonlinear logistic curves"
data: "August 2018"
output:
  rmarkdown::github_document:
    pandoc_args: "--webtex"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  comment = "#>", 
  collapse = TRUE,
  fig.width = 5,     
  fig.asp = 0.618,
  fig.path = "./figures/2018-08-00-nonlinear-logistics/"
)
```

Hustad et al. (2018/in press) uses a logistic curve with the form:

$$f(\text{time}) = \frac{\text{asymptote}}{1 + \exp({\frac{\text{mid}-\text{time}}{\text{scale}})}}$$

where *asymptote* is the ceiling or plateau of the curve, *scale* controls the
slope of the curve, *mid* is the point where the curve is steepest.



```{r}
library(tidyverse)

# Generate a single curve
generate_curve <- function(time = -10:10, mid = NULL, 
                           asymptote = NULL, scale = NULL) {
  
  # If no value is given, draw one from a distribution
  mid <- mid %||% rnorm(1, 0, 3)
  asymptote <- asymptote %||% rbeta(1, 2, 1)
  scale <- scale %||% rnorm(1, 2, .5)
  
  y <- asymptote / (1 + exp((mid - time) / scale))
  
  data_frame(
    time = time, 
    proportion = y, 
    asymptote = asymptote, 
    scale = scale, 
    min_proportion = min(y), 
    mid = mid)  
}

generate_n_curves <- function(n, time = -10:10, mid = NULL, 
                              asymptote = NULL, scale = NULL) {
  f <- function() {
    generate_curve(
      time = time, mid = mid, 
      asymptote = asymptote, scale = scale)
  }
  
  dplyr::bind_rows(
    # ignore the sequence number by using a dummy argument x
    lapply(seq_len(n), function(x) f()), 
    .id = "sim"
  )
}
```

Simulate 40 curves.

```{r forty-curves}
forty <- generate_n_curves(40)
ggplot(forty) + 
  aes(x = time, y = proportion, group = sim) + 
  geom_line() 
```

Test function. They should not exceed .7.

```{r forty-curves-point-7}
forty <- generate_n_curves(40, asymptote = .7)
ggplot(forty) + 
  aes(x = time, y = proportion, group = sim) + 
  geom_line() + 
  labs(caption = "asymptote fixed to .7")
```

What drives the starting value?

```{r starting-asymptote}
thousand <- generate_n_curves(1000)

p1 <- ggplot(thousand) + 
  aes(x = mid, y = min_proportion) + 
  geom_point(alpha = .01) + 
  labs(y = "min(proportion)")

p2 <- ggplot(thousand) + 
  aes(x = scale, y = min_proportion) + 
  geom_point(alpha = .01) + 
  labs(y = "min(proportion)")

library(patchwork)
p1 + p2 + 
  plot_annotation(
    title = "What sets the starting point for the curve?",
    subtitle = "Earlier crossovers (`mid`) and/or steeper slopes (`scale`)")
```

In the paper, the scale is not a random effect. Only the `mid` and `asymptote` are.

```{r scale-differences, fig.height=5, fig.width = 7}
fifty <- dplyr::bind_rows(
  generate_n_curves(50, scale = 0),
  generate_n_curves(50, scale = 1),
  generate_n_curves(50, scale = -1),
  generate_n_curves(50, scale = 3),
  generate_n_curves(50, scale = 5), 
  generate_n_curves(50, scale = 10), 
  .id = "scale_sim")

library(ggplot2)

ggplot(fifty) +
  aes(x = time, y = proportion, group = sim) +
  geom_line(color = "grey40", alpha = .5) + 
  facet_wrap("scale",labeller = label_both) + 
  labs(
    title = "Curves for fixed `scale` values",
    caption = "Other parameters simulated:\nasymptote ~ beta(2,1); mid ~ normal(0,3)")
```

